apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: imgprocessor
spec:
  tag: ${DATA_E2E_REGISTRY_USERNAME}/ml-image-processor
  builder:
    kind: ClusterBuilder
    name: base
  source:
    git:
      url: https://github.com/agapebondservant/ml-image-processing-app-pipelines.git
      revision: main
  cache:
    volume:
      size: 8G