apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: imgprocessor
spec:
  tag: ${DATA_E2E_REGISTRY_USERNAME}/ml-image-processor
  builder:
    kind: ClusterBuilder
    name: full
  source:
    git:
      url: https://github.com/agapebondservant/ml-image-processing-app-argopipelines.git
      revision: main
  cache:
    volume:
      size: 8G
  build:
    env:
      - name: "MLFLOW_TRACKING_URI"
        value: http://mlflow.${DATA_E2E_BASE_URL}
      - name: "MLFLOW_S3_ENDPOINT_URL"
        value: http://minio-ml.${DATA_E2E_BASE_URL}